#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ******************************************************************************
# Project: GeoTIFF ToolKit (GTTK)
# Author: Eric Robeck <robeckgeo@gmail.com>
#
# Copyright (c) 2026, Eric Robeck
# Licensed under the MIT License
# ******************************************************************************

"""
Help rendering for the GTTK command line.

Most ``optimize`` options have no fixed default: the value is chosen later by
``OptimizeArguments._resolve_defaults`` from ``--product-type`` and from the codec
that ends up selected.  Argparse cannot see that, so left alone it prints
``(default: None)`` for options that very much do have a default.

Rather than restate those rules in prose -- which is how the four existing copies of
them drifted apart -- everything here is generated by *calling the resolver*.
``_resolve_defaults`` touches no files, so a throwaway ``OptimizeArguments`` is a
complete and always-current answer to "what would GTTK choose here?".

Contents:
    GttkHelpFormatter: prints a default only when the default is the truth.
    default_clause: 'JPEG (image), DEFLATE (dem, error, scientific, thematic)'.
    profile_table: the per-product-type table shown in ``optimize``'s epilog.
    ShowDefaultsAction: backs ``--show-defaults``.
"""
import argparse
import logging
import re
from functools import lru_cache
from typing import Any, Dict, Optional, Sequence

import gttk.utils.optimize_constants as oc
from gttk.utils.optimize_constants import ProductType as PT

#: Product types in declaration order, used for grouping values in a help clause.
PRODUCT_TYPES = tuple(t.value for t in PT)

#: Order used by the epilog table: continuous surfaces first, then categorical.
TABLE_ORDER = (PT.DEM.value, PT.ERROR.value, PT.SCIENTIFIC.value,
               PT.IMAGE.value, PT.THEMATIC.value)

#: --vertical-srs is *required* for 'dem' rather than defaulted, so the probe has to
#: supply something.  It feeds no other resolved value.
_PROBE_SRS = 'EPSG:5703'

ABSENT = '-'

#: OptimizeArguments logs every rejection before raising.  While probing, a rejection
#: is one of the answers we are looking for, so it must not reach the console.
_ARGS_LOGGER = logging.getLogger('gttk.utils.script_arguments')


# --- Probing the real resolver ------------------------------------------------

def probe_defaults(product_type: str, **overrides):
    """A resolved OptimizeArguments for one product type, or None if the combination
    is rejected (LERC on imagery, say).

    The single way to ask "what would GTTK choose here?" without a raster: used by the
    generated help, by --show-defaults, and by the ArcGIS toolbox to pre-fill its
    dialog.  Imported lazily -- script_arguments pulls in GDAL, and this module is
    imported while the parser is still being built.
    """
    from gttk.utils.script_arguments import OptimizeArguments
    overrides.setdefault('vertical_srs', _PROBE_SRS)
    was_disabled = _ARGS_LOGGER.disabled
    _ARGS_LOGGER.disabled = True
    try:
        return OptimizeArguments(product_type=product_type, **overrides)
    except (ValueError, TypeError):
        return None
    finally:
        _ARGS_LOGGER.disabled = was_disabled


@lru_cache(maxsize=None)
def _resolved_pairs(field: str, types: Sequence[str], **overrides):
    """The cached form: a tuple, so nothing can mutate what the cache is holding."""
    return tuple((t, getattr(args, field, None) if args is not None else None)
                 for t in types
                 for args in (probe_defaults(t, **overrides),))


def resolved_by_type(field: str, types: Sequence[str] = PRODUCT_TYPES,
                     **overrides) -> Dict[str, Any]:
    """``{product_type: resolved value}`` for one OptimizeArguments field.

    A type whose combination the validator rejects maps to ``None``.  ``overrides``
    pins other flags, which is how a codec-conditional option can be described at
    all: ``resolved_by_type('predictor', algorithm='DEFLATE')`` answers "what
    predictor would each product type get, for a codec that uses one?".
    """
    return dict(_resolved_pairs(field, tuple(types), **overrides))


def fmt_value(value: Any, absent: str = ABSENT) -> str:
    """Render one resolved value for display."""
    if value is None:
        return absent
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return f'{value:g}'
    return str(value)


def default_clause(field: str, types: Sequence[str] = PRODUCT_TYPES,
                   absent: Optional[str] = None, **overrides) -> str:
    """A compact statement of one field's default across product types.

    ``'2 (dem, error), 1 (image, thematic), 3 (scientific)'``, collapsing to a bare
    ``'ALL_CPUS'`` when every type agrees.  Types whose value is ``None`` are omitted
    unless ``absent`` names them.
    """
    resolved = resolved_by_type(field, tuple(types), **overrides)
    if absent is None:
        resolved = {t: v for t, v in resolved.items() if v is not None}
    if not resolved:
        return ''
    distinct = {fmt_value(v, absent or ABSENT) for v in resolved.values()}
    if len(distinct) == 1:
        return distinct.pop()

    groups: Dict[str, list] = {}          # value -> types, in first-appearance order
    for t, v in resolved.items():
        groups.setdefault(fmt_value(v, absent or ABSENT), []).append(t)
    return ', '.join(f"{v} ({', '.join(ts)})" for v, ts in groups.items())


# --- The help formatter -------------------------------------------------------

class GttkHelpFormatter(argparse.ArgumentDefaultsHelpFormatter,
                        argparse.RawDescriptionHelpFormatter):
    """Prints a default only when the default is the truth.

    Stock ArgumentDefaultsHelpFormatter appends '(default: %(default)s)' to every
    optional, which is wrong three ways here: required arguments get a meaningless
    '(default: None)'; arguments resolved later from --product-type get
    '(default: None)' when a real value will in fact be chosen; and arguments whose
    help already states its default get it printed twice.

    RawDescriptionHelpFormatter is mixed in so the epilog's profile table keeps its
    column alignment.  Note that colourised help is a Python 3.14 stdlib feature of
    HelpFormatter itself -- subclassing keeps it, replacing the formatter loses it.
    """

    _STATES_DEFAULT = re.compile(r'\bDefaults?:', re.IGNORECASE)

    def _get_help_string(self, action):
        text = action.help or ''
        if action.required:
            return text                                  # '(default: None)' on -i is noise
        if action.default is None or action.default is argparse.SUPPRESS:
            return text                                  # deferred; the help text explains
        if action.nargs == 0 and action.default is False:
            return text                                  # store_true; obvious
        if '%(default)' in text or self._STATES_DEFAULT.search(text):
            return text                                  # already stated, don't say it twice
        return text + ' (default: %(default)s)'


# --- The epilog table ---------------------------------------------------------

_TABLE_COLUMNS = (
    # header,            field,                  overrides
    ('-a',               'algorithm',            {}),
    ('-p',               'predictor',            {}),
    ('-d',               'decimals',             {}),
    ('-z*',              'max_z_error',          {'algorithm': 'LERC'}),
    ('mask-nodata',      'mask_nodata',          {}),
    ('ovr-resampling',   'overview_resampling',  {}),
)


@lru_cache(maxsize=None)
def profile_table() -> str:
    """The per-product-type table for ``optimize``'s epilog.

    Every cell is read back from the resolver, so the table cannot drift from
    behaviour.  Cells show what a bare ``gttk optimize -t TYPE -i .. -o ..`` produces;
    the -z column is the exception, showing what LERC would use if selected.
    """
    headers = ['-t'] + [h for h, _, _ in _TABLE_COLUMNS]
    rows = []
    for t in TABLE_ORDER:
        row = [t]
        for _, field, overrides in _TABLE_COLUMNS:
            args = probe_defaults(t, **overrides)
            # A rejected combination (LERC on imagery) is 'n/a', not merely unset.
            row.append('n/a' if args is None else fmt_value(getattr(args, field, None)))
        rows.append(row)

    widths = [max(len(r[i]) for r in [headers] + rows) for i in range(len(headers))]
    def line(cells):
        return '  ' + '  '.join(c.ljust(w) for c, w in zip(cells, widths)).rstrip()

    return '\n'.join([
        'Product-type profiles - the values used when you omit the flag:',
        '',
        line(headers),
        *[line(r) for r in rows],
        '',
        '  -p/-d apply to LZW/DEFLATE/ZSTD only; -z* only when you select -a LERC,',
        '  which is not available for image and must stay 0 for thematic.',
        f"  -q is {default_clause('quality', algorithm='JPEG')} for JPEG/JXL; "
        f"-l is per codec: {default_clause('level', algorithm='DEFLATE')} (DEFLATE), "
        f"{default_clause('level', algorithm='ZSTD')} (ZSTD).",
        '  -p 3 falls back to 2 on integer data.  mask-alpha is True except thematic.',
        '  Run `gttk optimize --show-defaults dem` for the full resolved set.',
    ])


# --- --show-defaults ----------------------------------------------------------

#: Fields whose source holds whether or not a value was resolved.
_PROVENANCE_ALWAYS = {
    'nodata': 'inherited from the input file',
}

#: Rules _resolve_defaults applies that comparing across product types cannot reveal.
#: Consulted only once a value is actually in play, so an unused option still reads
#: as 'not used by <codec>'.
_PROVENANCE_WHEN_SET = {
    'level':              'codec default ({algorithm})',
    'quality':            'codec default ({algorithm})',
    'overview_compress':  'inherits --algorithm',
    'overview_predictor': 'inherits --predictor',
}

_SHOW_SECTIONS = (
    ('compression', (('--algorithm', 'algorithm'), ('--level', 'level'),
                     ('--predictor', 'predictor'), ('--decimals', 'decimals'),
                     ('--quality', 'quality'), ('--max-z-error', 'max_z_error'))),
    ('overviews', (('--overviews', 'overviews'),
                   ('--overview-resampling', 'overview_resampling'),
                   ('--overview-compress', 'overview_compress'),
                   ('--overview-predictor', 'overview_predictor'))),
    ('masking and nodata', (('--mask-alpha', 'mask_alpha'),
                            ('--mask-nodata', 'mask_nodata'), ('--nodata', 'nodata'))),
    ('output file', (('--cog', 'cog'), ('--tile-size', 'tile_size'),
                     ('--num-threads', 'num_threads'), ('--raster-type', 'raster_type'))),
)


def _provenance(field: str, args) -> str:
    """Where this value came from, derived rather than hand-written."""
    if field in _PROVENANCE_ALWAYS:
        return _PROVENANCE_ALWAYS[field]
    if getattr(args, field, None) is None:
        # Two different reasons a value is absent, and saying the wrong one misleads:
        # --decimals is unset for thematic because rounding class codes is meaningless,
        # not because DEFLATE ignores it.  If the same codec gives some *other* product
        # type a value, then it is the product type doing the excluding.
        elsewhere = resolved_by_type(field, algorithm=args.algorithm)
        if any(v is not None for v in elsewhere.values()):
            return f'not applicable to {args.product_type}'
        return f'not used by {args.algorithm}'
    if field in _PROVENANCE_WHEN_SET:
        return _PROVENANCE_WHEN_SET[field].format(algorithm=args.algorithm)
    across = set(fmt_value(v) for v in resolved_by_type(field).values())
    return 'varies by --product-type' if len(across) > 1 else 'always'


def render_show_defaults(which: str = 'all') -> str:
    """The block printed by ``--show-defaults``: every value that will be used, and
    where each one came from."""
    types = TABLE_ORDER if which in (None, 'all') else (which,)
    blocks = []
    for product_type in types:
        args = probe_defaults(product_type)
        if args is None:                                  # cannot happen for a bare type
            continue
        lines = [f'gttk optimize -t {product_type}  -  settings that will be used', '']
        for title, fields in _SHOW_SECTIONS:
            lines.append(f'  {title}')
            for flag, field in fields:
                value = fmt_value(getattr(args, field, None))
                lines.append(f'    {flag:<22} {value:<11} {_provenance(field, args)}')
        lines.append('')
        if product_type == PT.DEM.value:
            lines.append("  --vertical-srs is required for 'dem'.")
        lines.append('  --predictor 3 falls back to 2 on integer rasters.')
        lines.append('  Report and metadata options are static; see `gttk optimize -h`.')
        blocks.append('\n'.join(lines))
    return '\n\n'.join(blocks)


class ShowDefaultsAction(argparse.Action):
    """``--show-defaults [TYPE]``: print the resolved settings and exit.

    Registered with ``dest=argparse.SUPPRESS`` -- main() splats ``vars(args)`` into
    OptimizeArguments, so a dest that is not a dataclass field would be a TypeError on
    every ordinary run.  Exiting from inside the action also bypasses argparse's
    required= checks, the same way --help does, so -i/-o/-t need not be supplied.
    """

    def __init__(self, option_strings, dest=argparse.SUPPRESS, nargs='?',
                 const='all', default=argparse.SUPPRESS, **kwargs):
        super().__init__(option_strings, dest, nargs=nargs, const=const,
                         default=default, **kwargs)

    def __call__(self, parser, namespace, values, option_string=None):
        print(render_show_defaults(values or 'all'))
        parser.exit()
