#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ******************************************************************************
# Project: GeoTIFF ToolKit (GTTK)
# Author: Eric Robeck <robeckgeo@gmail.com>
#
# Copyright (c) 2025, Eric Robeck
# Licensed under the MIT License
# ******************************************************************************

"""
Tests for Report Formatters.

This module tests the report formatter classes that orchestrate report assembly
and formatting for different output types (Markdown, HTML).
"""

import pytest
from gttk.utils.report_formatters import (
    ReportFormatter,
    MarkdownReportFormatter,
    HtmlReportFormatter
)
from gttk.utils.data_models import (
    TiffTag,
    TiffTagsData,
    StatisticsData,
    GeoKey
)


class TestMarkdownReportFormatter:
    """Test MarkdownReportFormatter class."""
    
    def test_instantiation(self):
        """Test creating a MarkdownReportFormatter instance."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        assert formatter.filename == "test.tif"
        assert formatter.sections == []
        assert formatter.report_title == "Metadata Report"
        assert formatter.include_title is False
    
    def test_add_section(self):
        """Test adding sections to the formatter."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        # Create test data
        tags = [
            TiffTag(code=256, name="ImageWidth", value=1024),
            TiffTag(code=257, name="ImageLength", value=1024)
        ]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        
        # Add section
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        assert len(formatter.sections) == 1
        assert formatter.sections[0].id == 'tags'
        assert formatter.sections[0].title == 'TIFF Tags'
        assert formatter.sections[0].data == tags_data
    
    def test_add_section_with_none_data_skips(self):
        """Test that sections with None data are not added."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        # Try to add section with None data
        formatter.add_section('tags', 'TIFF Tags', 'Tags', None)
        
        assert len(formatter.sections) == 0
    
    def test_render_header_with_toc(self):
        """Test rendering header with table of contents."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        # Add some sections
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        geokeys = [GeoKey(id=1024, name="GTModelTypeGeoKey", value=2, value_text="2 (ModelTypeProjected)")]
        formatter.add_section('geokeys', 'GeoKeys', 'GeoKeys', geokeys)
        
        # Render header
        header = formatter._render_header()
        
        # Check TOC exists
        assert "## Table of Contents" in header
        assert "[TIFF Tags](#tiff-tags)" in header
        assert "[GeoKeys](#geokeys)" in header
    
    def test_render_header_with_title_enabled(self):
        """Test rendering header with title when include_title is True."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        formatter.include_title = True
        formatter.report_title = "Custom Report"
        
        header = formatter._render_header()
        
        assert "# Custom Report: test.tif" in header
    
    def test_render_header_without_title(self):
        """Test rendering header without title when include_title is False."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        formatter.include_title = False
        
        header = formatter._render_header()
        
        # Should not contain the title header
        assert "# Metadata Report:" not in header
    
    def test_render_footer(self):
        """Test rendering footer."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        footer = formatter._render_footer()
        
        # Check footer contains expected elements
        assert "---" in footer
        assert "Report generated by" in footer
        assert "GeoTIFF ToolKit" in footer
        assert "https://github.com/robeckgeo/gttk" in footer
    
    def test_format_complete_report(self):
        """Test generating a complete markdown report."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        # Add test sections
        tags = [
            TiffTag(code=256, name="ImageWidth", value=1024),
            TiffTag(code=257, name="ImageLength", value=1024)
        ]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        # Generate report
        report = formatter.format()
        
        # Verify structure
        assert "## Table of Contents" in report
        assert "## TIFF Tags" in report
        assert "ImageWidth" in report
        assert "ImageLength" in report
        assert "Report generated by" in report


class TestHtmlReportFormatter:
    """Test HtmlReportFormatter class."""
    
    def test_instantiation(self):
        """Test creating an HtmlReportFormatter instance."""
        formatter = HtmlReportFormatter(filename="test.tif", theme="material_light")
        assert formatter.filename == "test.tif"
        assert formatter.theme == "material_light"
        assert formatter.sections == []
        assert formatter.menu_items == []
        assert formatter.renderer.enable_html_styling is True
    
    def test_instantiation_with_dark_theme(self):
        """Test creating formatter with dark theme."""
        formatter = HtmlReportFormatter(filename="test.tif", theme="material_dark")
        assert formatter.theme == "material_dark"
    
    def test_render_header_returns_empty(self):
        """Test that _render_header returns empty string for HTML."""
        formatter = HtmlReportFormatter(filename="test.tif")
        header = formatter._render_header()
        assert header == ""
    
    def test_render_footer_returns_empty(self):
        """Test that _render_footer returns empty string for HTML."""
        formatter = HtmlReportFormatter(filename="test.tif")
        footer = formatter._render_footer()
        assert footer == ""
    
    def test_menu_items_populated_during_rendering(self):
        """Test that menu items are populated when rendering sections."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        # Add test section
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        # Render section to populate menu items
        section = formatter.sections[0]
        formatter._render_section(section)
        
        # Check menu item was created
        assert len(formatter.menu_items) == 1
        assert formatter.menu_items[0].anchor == 'tags'
        assert formatter.menu_items[0].name == 'Tags'
        assert formatter.menu_items[0].title == 'TIFF Tags'
    
    def test_format_generates_complete_html(self):
        """Test that format() generates a complete HTML document."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        # Add test section
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        # Generate HTML
        html = formatter.format()
        
        # Verify HTML structure
        assert html.startswith("<!DOCTYPE html>")
        assert "<html lang=\"en\">" in html
        assert "<head>" in html
        assert "<title>Metadata: test.tif</title>" in html
        assert "<body>" in html
        assert "</body>" in html
        assert "</html>" in html
        
        # Verify content elements
        assert "ImageWidth" in html
        # Value is formatted with thousand separator
        assert "1,024" in html
    
    def test_format_includes_css(self):
        """Test that generated HTML includes CSS styles."""
        formatter = HtmlReportFormatter(filename="test.tif")
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        html = formatter.format()
        
        assert "<style>" in html
        assert "</style>" in html
    
    def test_format_includes_javascript(self):
        """Test that generated HTML includes JavaScript."""
        formatter = HtmlReportFormatter(filename="test.tif")
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        html = formatter.format()
        
        assert "<script>" in html
        assert "</script>" in html
    
    def test_format_includes_navigation(self):
        """Test that generated HTML includes navigation menu."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        # Add multiple sections
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        geokeys = [GeoKey(id=1024, name="GTModelTypeGeoKey", value=2, value_text="2 (ModelTypeProjected)")]
        formatter.add_section('geokeys', 'GeoKeys', 'GeoKeys', geokeys)
        
        html = formatter.format()
        
        # Check navigation exists
        assert "<ul class=\"menu-bar\">" in html
        assert "menu-item" in html
        assert "menu-link" in html
    
    def test_markdown_to_html_conversion(self):
        """Test that markdown is correctly converted to HTML."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        markdown = "## Test Section\n\nThis is a test paragraph."
        html = formatter._markdown_to_html(markdown)
        
        assert "<h2" in html
        assert "Test Section" in html
        assert "<p>" in html or "test paragraph" in html.lower()
    
    def test_markdown_table_conversion(self):
        """Test that markdown tables are converted to HTML tables."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        markdown = """| Column1 | Column2 |
|---------|---------|
| Value1  | Value2  |"""
        
        html = formatter._markdown_to_html(markdown)
        
        assert "<table>" in html
        assert "<thead>" in html
        assert "<tbody>" in html
        assert "Column1" in html
        assert "Value1" in html
    
    def test_anchor_map_populated(self):
        """Test that anchor_map is populated for navigation."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        # Render section to populate anchor map
        section = formatter.sections[0]
        formatter._render_section(section)
        
        assert "TIFF Tags" in formatter.anchor_map
        assert formatter.anchor_map["TIFF Tags"] == "tags"
    
    def test_report_title_in_header(self):
        """Test that report title appears in HTML header."""
        formatter = HtmlReportFormatter(filename="test.tif")
        formatter.report_title = "Custom Report Title"
        
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        html = formatter.format()
        
        # Check title in HTML head
        assert "<title>Custom: test.tif</title>" in html
        
        # Check title in report header
        assert "Custom Report Title" in html


class TestReportFormatterBase:
    """Test abstract ReportFormatter base class."""
    
    def test_cannot_instantiate_abstract_class(self):
        """Test that abstract ReportFormatter cannot be instantiated directly."""
        from gttk.utils.section_renderers import MarkdownRenderer
        
        # Abstract class should raise TypeError when instantiated
        with pytest.raises(TypeError, match="abstract"):
            # This should fail because ReportFormatter is abstract
            formatter = ReportFormatter.__new__(ReportFormatter)
            formatter.__init__(MarkdownRenderer())
    
    def test_add_section_with_data(self):
        """Test add_section adds section when data is provided."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        assert len(formatter.sections) == 1
        assert formatter.sections[0].enabled is True
    
    def test_prepare_rendering_sets_sections(self):
        """Test that prepare_rendering sets sections in renderer."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        formatter.prepare_rendering()
        
        # Verify renderer has sections set
        assert 'tags' in formatter.renderer.requested_sections


class TestSpecialCharacterHandling:
    """Test special character handling in reports."""
    
    def test_markdown_pipe_characters_in_values(self):
        """Test that pipe characters in values don't break tables."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        # Create tag with pipe character in value
        tags = [
            TiffTag(code=270, name="ImageDescription", value="Test | Value | With | Pipes")
        ]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        report = formatter.format()
        
        # Verify report is generated without errors
        assert "ImageDescription" in report
        # The formatter should handle this gracefully
    
    def test_markdown_special_characters_in_values(self):
        """Test handling of special markdown characters."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        # Create tags with special characters
        tags = [
            TiffTag(code=270, name="ImageDescription", value="Test *italic* and **bold**"),
            TiffTag(code=271, name="Make", value="Test [link] and `code`")
        ]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        report = formatter.format()
        
        # Verify report is generated
        assert "ImageDescription" in report
        assert "Make" in report
    
    def test_html_escaping_in_values(self):
        """Test that HTML special characters are handled in HTML reports."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        # Create tags with HTML special characters
        tags = [
            TiffTag(code=270, name="ImageDescription", value="Test <tag> & \"quotes\"")
        ]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        html = formatter.format()
        
        # Verify HTML is generated without breaking structure
        assert "ImageDescription" in html
        assert "</html>" in html  # Document is complete


class TestReportNavigation:
    """Test report navigation and anchor generation."""
    
    def test_markdown_toc_anchors_match_headers(self):
        """Test that TOC anchors match section headers."""
        formatter = MarkdownReportFormatter(filename="test.tif")
        
        # Add sections with various title formats
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags (IFD 0)", footer=None)
        formatter.add_section('tags', 'TIFF Tags (IFD 0)', 'Tags', tags_data)
        
        report = formatter.format()
        
        # Check TOC link
        assert "[TIFF Tags (IFD 0)](#tiff-tags-ifd-0)" in report
        
        # Check section header exists
        assert "## TIFF Tags (IFD 0)" in report
    
    def test_html_navigation_anchors(self):
        """Test that HTML navigation anchors match section IDs."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        html = formatter.format()
        
        # Check navigation link
        assert 'href="#tags"' in html
        
        # Check section anchor
        assert 'id="tags"' in html
    
    def test_multiple_sections_navigation(self):
        """Test navigation with multiple sections."""
        formatter = HtmlReportFormatter(filename="test.tif")
        
        # Add multiple sections
        tags = [TiffTag(code=256, name="ImageWidth", value=1024)]
        tags_data = TiffTagsData(tags=tags, title="TIFF Tags", footer=None)
        formatter.add_section('tags', 'TIFF Tags', 'Tags', tags_data)
        
        geokeys = [GeoKey(id=1024, name="GTModelTypeGeoKey", value=2, value_text="2 (ModelTypeProjected)")]
        formatter.add_section('geokeys', 'GeoKeys', 'GeoKeys', geokeys)
        
        stats_data = StatisticsData(
            title="Statistics",
            headers=["Statistic", "Band 1"],
            data=[]
        )
        formatter.add_section('statistics', 'Statistics', 'Stats', stats_data)
        
        html = formatter.format()
        
        # Verify all navigation links exist
        assert 'href="#tags"' in html
        assert 'href="#geokeys"' in html
        assert 'href="#statistics"' in html
        
        # Verify all section anchors exist
        assert 'id="tags"' in html
        assert 'id="geokeys"' in html
        assert 'id="statistics"' in html